#!/bin/bash

. ../cfg/current_cfg.sh

REPLICAS_ADMIN_PORTS=( "${REPLICAS_POOL_ADMIN_PORTS[@]}" )
REPLICAS_TYPE="POOL"

REPLICAS_START_NUMBER="${#REPLICAS_MANAGE_ADMIN_PORTS[@]}"
((REPLICAS_START_NUMBER++))

. ./start_replicas.sh $REPLICAS_START_NUMBER
